/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/wheel.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/wheel.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="slot1"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle004"
            geometry={nodes.Circle004.geometry}
            material={materials.slot1m}
          />
          <mesh
            name="Circle004_1"
            geometry={nodes.Circle004_1.geometry}
            material={materials.emmision}
          />
        </group>
        <group
          name="slot2"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle005"
            geometry={nodes.Circle005.geometry}
            material={materials.slot2m}
          />
          <mesh
            name="Circle005_1"
            geometry={nodes.Circle005_1.geometry}
            material={materials['emmision.001']}
          />
        </group>
        <group
          name="slot3"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle007"
            geometry={nodes.Circle007.geometry}
            material={materials.slot3m}
          />
          <mesh
            name="Circle007_1"
            geometry={nodes.Circle007_1.geometry}
            material={materials['emmision.002']}
          />
        </group>
        <group
          name="slot4"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle008"
            geometry={nodes.Circle008.geometry}
            material={materials.slot4m}
          />
          <mesh
            name="Circle008_1"
            geometry={nodes.Circle008_1.geometry}
            material={materials['emmision.003']}
          />
        </group>
        <group
          name="slot5"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle010"
            geometry={nodes.Circle010.geometry}
            material={materials.slot5m}
          />
          <mesh
            name="Circle010_1"
            geometry={nodes.Circle010_1.geometry}
            material={materials['emmision.004']}
          />
        </group>
        <group
          name="slot6"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle013"
            geometry={nodes.Circle013.geometry}
            material={materials.slot6m}
          />
          <mesh
            name="Circle013_1"
            geometry={nodes.Circle013_1.geometry}
            material={materials['emmision.005']}
          />
        </group>
        <group
          name="slot7"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle014"
            geometry={nodes.Circle014.geometry}
            material={materials.slot7m}
          />
          <mesh
            name="Circle014_1"
            geometry={nodes.Circle014_1.geometry}
            material={materials['emmision.006']}
          />
        </group>
        <group
          name="slot8"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle015"
            geometry={nodes.Circle015.geometry}
            material={materials.slot8m}
          />
          <mesh
            name="Circle015_1"
            geometry={nodes.Circle015_1.geometry}
            material={materials['emmision.007']}
          />
        </group>
        <group
          name="slot9"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle016"
            geometry={nodes.Circle016.geometry}
            material={materials.slot9m}
          />
          <mesh
            name="Circle016_1"
            geometry={nodes.Circle016_1.geometry}
            material={materials['emmision.008']}
          />
        </group>
        <group
          name="slot10"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle017"
            geometry={nodes.Circle017.geometry}
            material={materials.slot10m}
          />
          <mesh
            name="Circle017_1"
            geometry={nodes.Circle017_1.geometry}
            material={materials['emmision.009']}
          />
        </group>
        <group
          name="slot11"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle018"
            geometry={nodes.Circle018.geometry}
            material={materials.slot11m}
          />
          <mesh
            name="Circle018_1"
            geometry={nodes.Circle018_1.geometry}
            material={materials['emmision.010']}
          />
        </group>
        <group
          name="slot12"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle022"
            geometry={nodes.Circle022.geometry}
            material={materials.slot12m}
          />
          <mesh
            name="Circle022_1"
            geometry={nodes.Circle022_1.geometry}
            material={materials['emmision.011']}
          />
        </group>
        <group
          name="slot13"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle024"
            geometry={nodes.Circle024.geometry}
            material={materials.slot13m}
          />
          <mesh
            name="Circle024_1"
            geometry={nodes.Circle024_1.geometry}
            material={materials['emmision.012']}
          />
        </group>
        <group
          name="slot14"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle025"
            geometry={nodes.Circle025.geometry}
            material={materials.slot14m}
          />
          <mesh
            name="Circle025_1"
            geometry={nodes.Circle025_1.geometry}
            material={materials['emmision.013']}
          />
        </group>
        <group
          name="slot15"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle026"
            geometry={nodes.Circle026.geometry}
            material={materials.slot15m}
          />
          <mesh
            name="Circle026_1"
            geometry={nodes.Circle026_1.geometry}
            material={materials['emmision.014']}
          />
        </group>
        <group
          name="slot16"
          position={[0, 0, -0.278]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.018}
        >
          <mesh
            name="Circle027"
            geometry={nodes.Circle027.geometry}
            material={materials.slot16m}
          />
          <mesh
            name="Circle027_1"
            geometry={nodes.Circle027_1.geometry}
            material={materials['emmision.015']}
          />
        </group>
        <group
          name="NurbsPath002"
          position={[-0.044, 5.419, 1.034]}
          rotation={[1.992, -0.293, 0]}
          scale={[0.184, 0.153, 0.148]}
        >
          <mesh
            name="NurbsPath010"
            geometry={nodes.NurbsPath010.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="NurbsPath010_1"
            geometry={nodes.NurbsPath010_1.geometry}
            material={materials['Material.005']}
          />
        </group>
        <mesh
          name="Circle002"
          geometry={nodes.Circle002.geometry}
          material={nodes.Circle002.material}
          position={[-0.103, -0.395, -0.192]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={4.014}
        />
        <group
          name="Circle009"
          position={[0, -4.974, -1.411]}
          rotation={[-Math.PI, 0, 0]}
          scale={[1.041, 0.742, 1.041]}
        >
          <mesh
            name="Circle009_1"
            geometry={nodes.Circle009_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Circle009_2"
            geometry={nodes.Circle009_2.geometry}
            material={materials['Material.004']}
          />
        </group>
        <mesh
          name="NurbsPath027"
          geometry={nodes.NurbsPath027.geometry}
          material={materials['Material.001']}
          rotation={[Math.PI / 2, -0.127, 0]}
          scale={[0.255, 0.213, 0.205]}
        />
        <group
          name="NurbsPath028"
          position={[0, 0, -0.112]}
          rotation={[Math.PI / 2, -0.127, 0]}
          scale={[0.255, 0.213, 0.205]}
        >
          <mesh
            name="NurbsPath028_1"
            geometry={nodes.NurbsPath028_1.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name="NurbsPath028_2"
            geometry={nodes.NurbsPath028_2.geometry}
            material={materials['Material.007']}
          />
        </group>
        <mesh
          name="NurbsPath030"
          geometry={nodes.NurbsPath030.geometry}
          material={materials['Material.001']}
          rotation={[Math.PI / 2, -0.127, 0]}
          scale={[0.255, 0.213, 0.205]}
        />
        <mesh
          name="NurbsPath032"
          geometry={nodes.NurbsPath032.geometry}
          material={materials['Material.001']}
          rotation={[Math.PI / 2, -0.127, 0]}
          scale={[0.255, 0.213, 0.205]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/wheel.glb')
